### ISSUE TITLE
IE10+ select element

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#150]
`appearance: none` isn't supported by IE10+, but there is sort of a `:-ms-` equivalent

```css
&::-ms-expand {
    display: none;
}
```
