### ISSUE TITLE
:focus style

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#291]
(Details TBD)

```scss
[contentEditable=true]:focus,
[href]:focus,
[tabindex]:focus,
button:not([disabled]):focus,
iframe:focus,
input:not([disabled]):focus,
select:not([disabled]):focus,
textarea:not([disabled]):focus {
  outline: 3px solid #009afa; 
    // Blue 40v (#009afa) 
    // Alt Blue: (#2491ff)
    // Orange: (#eb8028) 
    // Alt Orange: (#FAAF00) 
  // outline-offset: 2px;
    // Use for buttons
}
```
