### ISSUE TITLE
a11y reduced motion

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#360]
### Task
Several components already make use use of the `prefers-reduced-motion` media query. This issue is intended to revisit all components use of animating properties and adjust if necessary.

### Related Issues

This came to focus during research and design for #357, #356, [ASC-222](https://issues.tools.fsa.usda.gov/browse/ASC-222), [ASC-215](https://issues.tools.fsa.usda.gov/browse/ASC-215), 

### Example

```scss
.thing {
  animation: anim-name 2.33s ease-in infinite;
  @media (prefers-reduced-motion: reduce) {
    animation: none;
    // or perhaps reduce its timing for less dizzying effect
    animation-duration: 6s;
  }
}
```

### Background

* https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity/
* https://caniuse.com/#search=prefers-reduced-motion
