### ISSUE TITLE
abbr border-color

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#374]
From [SPAR's `shame.scss`](https://bitbucket.fpac.usda.gov/projects/SPA/repos/fpac-spa-reference-app-ui/):

```scss
abbr[title],
acronym[title],
dfn[title] {
  border-bottom-color: $color-fsa-tertiary-200;
}
```
