### ISSUE TITLE
Inline Alert: text size enhancements

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#375]
From [SPAR's `shame.scss`](https://bitbucket.fpac.usda.gov/projects/SPA/repos/fpac-spa-reference-app-ui/):

```scss
.fsa-alert {
  &__heading {
    font-size: $font-size-3;
  }
  &__text {
    font-size: $font-size-2;
    & + & {
      margin-top: 1em;
    }
  }
}
```
