### ISSUE TITLE
<hr> clear

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#376]
From [SPAR's `shame.scss`](https://bitbucket.fpac.usda.gov/projects/SPA/repos/fpac-spa-reference-app-ui/):

```scss
hr {
  clear: both
}
```
