### ISSUE TITLE
#main min-height

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#377]
From [SPAR's `shame.scss`](https://bitbucket.fpac.usda.gov/projects/SPA/repos/fpac-spa-reference-app-ui/):

```scss
#main-content {
  min-height: 25vh;
}
```
