### ISSUE TITLE
Breadcrumb: single item

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#402]
Port over SPAR's `:only-child` implementation.

Presumptive:

```scss
.fsa-breadcrumb__link {
  display: inline-flex;
  align-items: center;
}

.fsa-breadcrumb__item:only-child {

  display: inline-block;
  align-items: center;

  &:after {
    display: none;
  }

  .fsa-breadcrumb__link:before {
    content: '';
    display: block;
    width: $size-default;
    height: $size-default;
    margin-right: $size-base;
    background-image: url('#{$image-path}/chevron-left--link.svg');
    background-size: 100%; // fallback
    background-size: contain;
  }

}

```
