### ISSUE TITLE
List Style Types

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#497]
The following got broken somehow

```scss
[type="a"] {
  list-style-type: lower-alpha;
}
[type="A"] {
  list-style-type: upper-alpha;
}
[type="i"] {
  list-style-type: lower-roman;
}
[type="I"] {
  list-style-type: upper-roman;
}

```
